apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-dumper
  labels:
    tags.datadoghq.com/env: "development"
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: "development"
