apiVersion: apps/v1
kind: CronJob
metadata:
  name: not-important
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/tls-secret: "vault-tls-secret"
            vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-cache-enable: "true"
            vault.hashicorp.com/agent-cache-use-auto-auth-token: force
            vault.hashicorp.com/agent-pre-populate-only: "true" # disable the sidecar, only populate the secret once, otherwise the job will never end
