apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner
  annotations:
    tubi/enable-runner: sysbox
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::370025973162:role/testing-arc-hello-world-runner
    spec:
      repository: adRise/hello-world
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "1"
          memory: "1Gi"
