apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world
spec:
  # template:
  #   spec:
  #     containers:
  #     - name: nginx
  #       image: 370025973162.dkr.ecr.us-east-2.amazonaws.com/nginx:1.18
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 1m

      canaryMetadata:
        annotations:
          ad.datadoghq.com/tags: '{"role": "canary"}'
      stableMetadata:
        annotations:
          ad.datadoghq.com/tags: '{"role": "stable"}'
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world
  selector:
    matchLabels:
      app: hello-world
