apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    'consul.hashicorp.com/service-sync': 'false'
    dong-test: true
spec:
  clusterIP: None
  selector:
    app: hello-world
  ports:
  - name: app
    port: 8080
  - name: envoy
    port: 8001
