apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/vault.yaml
    target:
      kind: Deployment
      annotationSelector: tubi/enable-vault=enabled
  - path: patches/vault.yaml
    target:
      kind: DaemonSet
      annotationSelector: tubi/enable-vault=enabled
  - path: patches/vault.yaml
    target:
      kind: ModelSetDeployment
      annotationSelector: tubi/enable-vault=enabled
  - path: patches/vault.yaml
    target:
      kind: StatefulSet
      annotationSelector: tubi/enable-vault=enabled
  - path: patches/vault-job.yaml
    target:
      kind: Job
      annotationSelector: tubi/enable-vault=enabled
  - path: patches/vault-cronjobs.yaml
    target:
      kind: CronJob
      annotationSelector: tubi/enable-vault=enabled
  - path: patches/vault-runnerdeployment.yaml
    target:
      kind: RunnerDeployment
      annotationSelector: tubi/enable-vault=enabled
