apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: datadog-metrics-example
resources:
- resources/deployment.yaml

configMapGenerator:
- name: server-py
  files:
    - files/server.py
